<a href="https://colab.research.google.com/github/kkumarisfdc/Kiran-s_Portfolio/blob/main/K_mer_%26_Dinucleotide_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from collections import Counter

grna_data = {
"gRNA_ID": [
"gRNA1","gRNA2","gRNA3","gRNA4","gRNA5",
"gRNA6","gRNA7","gRNA8","gRNA9","gRNA10"

],

"Sequence":[
"GAGTCCGAGCAGAAGAAGAA",
"GCTGATCGTAGCTAGCTAGC",
"ATCGGCTAGCTAGGCTAGCT",
"CGTAGCTAGCGATCGATGCA",
"TCGATCGATCGTAGCTAGCA",
"AGCTAGCTAGCATCGATCGA",
"CGATCGTAGCTAGCTAGCTA",
"GCTAGCTAGCATCGTAGCTA",
"TAGCTAGCTAGCGATCGATC",
"ATCGTAGCTAGCATCGTAGC"
]
}

df = pd.DataFrame(grna_data)

df

  gRNA_ID              Sequence
0   gRNA1  GAGTCCGAGCAGAAGAAGAA
1   gRNA2  GCTGATCGTAGCTAGCTAGC
2   gRNA3  ATCGGCTAGCTAGGCTAGCT
3   gRNA4  CGTAGCTAGCGATCGATGCA
4   gRNA5  TCGATCGATCGTAGCTAGCA
5   gRNA6  AGCTAGCTAGCATCGATCGA
6   gRNA7  CGATCGTAGCTAGCTAGCTA
7   gRNA8  GCTAGCTAGCATCGTAGCTA
8   gRNA9  TAGCTAGCTAGCGATCGATC
9  gRNA10  ATCGTAGCTAGCATCGTAGC

In [ ]:
df = pd.concat([df]*10, ignore_index=True)

df["gRNA_ID"]=["gRNA_"+str(i+1) for i in range(len(df))]

df.head()

  gRNA_ID              Sequence
0  gRNA_1  GAGTCCGAGCAGAAGAAGAA
1  gRNA_2  GCTGATCGTAGCTAGCTAGC
2  gRNA_3  ATCGGCTAGCTAGGCTAGCT
3  gRNA_4  CGTAGCTAGCGATCGATGCA
4  gRNA_5  TCGATCGATCGTAGCTAGCA

In [ ]:
print(df.shape)

(100, 2)

In [ ]:
df.head()

  gRNA_ID              Sequence
0  gRNA_1  GAGTCCGAGCAGAAGAAGAA
1  gRNA_2  GCTGATCGTAGCTAGCTAGC
2  gRNA_3  ATCGGCTAGCTAGGCTAGCT
3  gRNA_4  CGTAGCTAGCGATCGATGCA
4  gRNA_5  TCGATCGATCGTAGCTAGCA

In [ ]:
def get_dinucleotides(sequence):

    dinucleotides = []

    for i in range(len(sequence)-1):

        dinucleotides.append(sequence[i:i+2])

    return dinucleotides

In [ ]:
sequence= "ATCGAT"

pairs = get_dinucleotides(sequence)

print(pairs)

['AT', 'TC', 'CG', 'GA', 'AT']

In [ ]:
def dinucleotide_frequency(sequence):
    pairs = get_dinucleotides(sequence)

    counts = Counter(pairs)

    total = len(pairs)

    frequency = {}

    for pair in counts:

        frequency[pair] = counts [pair]/total

    return frequency

In [ ]:

sequence = "ATCGAT"

freq = dinucleotide_frequency(sequence)

print(freq)

{'AT': 0.4, 'TC': 0.2, 'CG': 0.2, 'GA': 0.2}

In [ ]:

bases = ["A","T","G","C"]
all_pairs = []

for b1 in bases:
  for b2 in bases:
    all_pairs.append(b1+b2)
print(all_pairs)

['AA', 'AT', 'AG', 'AC', 'TA', 'TT', 'TG', 'TC', 'GA', 'GT', 'GG', 'GC', 'CA', 'CT', 'CG', 'CC']

In [ ]:
feature_table =[]
for seq in df["Sequence"]:
  freq = dinucleotide_frequency(seq)
  row =[]
  for pair in all_pairs:
    if pair in freq:
      row.append(freq.get(pair,0))
    else:
      row.append(0)
  feature_table.append(row)

In [ ]:
feature_df = pd.DataFrame(feature_table,columns=all_pairs)
feature_df.head()

,AA,AT,AG,AC,TA,TT,TG,TC,GA,GT,GG,GC,CA,CT,CG,CC
0,0.157895,0.000000,0.263158,0,0.000000,0,0.000000,0.052632,0.263158,0.052632,0.000000,0.052632,0.052632,0.000000,0.052632,0.052632
1,0.000000,0.052632,0.157895,0,0.157895,0,0.052632,0.052632,0.052632,0.052632,0.000000,0.210526,0.000000,0.157895,0.052632,0.000000
2,0.000000,0.052632,0.157895,0,0.157895,0,0.000000,0.052632,0.000000,0.000000,0.105263,0.210526,0.000000,0.210526,0.052632,0.000000
3,0.000000,0.105263,0.105263,0,0.105263,0,0.052632,0.052632,0.105263,0.052632,0.000000,0.157895,0.052632,0.052632,0.157895,0.000000
4,0.000000,0.105263,0.105263,0,0.105263,0,0.000000,0.157895,0.105263,0.052632,0.000000,0.105263,0.052632,0.052632,0.157895,0.000000

In [ ]:
final_df = pd.concat([df,feature_df],axis=1)
final_df.head()

,gRNA_ID,Sequence,AA,AT,AG,AC,TA,TT,TG,TC,GA,GT,GG,GC,CA,CT,CG,CC
0,gRNA_1,GAGTCCGAGCAGAAGAAGAA,0.157895,0.000000,0.263158,0,0.000000,0,0.000000,0.052632,0.263158,0.052632,0.000000,0.052632,0.052632,0.000000,0.052632,0.052632
1,gRNA_2,GCTGATCGTAGCTAGCTAGC,0.000000,0.052632,0.157895,0,0.157895,0,0.052632,0.052632,0.052632,0.052632,0.000000,0.210526,0.000000,0.157895,0.052632,0.000000
2,gRNA_3,ATCGGCTAGCTAGGCTAGCT,0.000000,0.052632,0.157895,0,0.157895,0,0.000000,0.052632,0.000000,0.000000,0.105263,0.210526,0.000000,0.210526,0.052632,0.000000
3,gRNA_4,CGTAGCTAGCGATCGATGCA,0.000000,0.105263,0.105263,0,0.105263,0,0.052632,0.052632,0.105263,0.052632,0.000000,0.157895,0.052632,0.052632,0.157895,0.000000
4,gRNA_5,TCGATCGATCGTAGCTAGCA,0.000000,0.105263,0.105263,0,0.105263,0,0.000000,0.157895,0.105263,0.052632,0.000000,0.105263,0.052632,0.052632,0.157895,0.000000

In [ ]:
def nucleotide_frequency(sequence):

  count = Counter(sequence)

  total = len(sequence)

  freq = {}

  for base in ["A","T","G","C"]:

    freq[base] = count[base]/total

  return freq

In [ ]:
def odds_ratio(sequence):

  mono = nucleotide_frequency(sequence)

  di = dinucleotide_frequency(sequence)

  odds = {}

  for pair in all_pairs:
    observed = di.get(pair,0)

    expected = mono[pair[0]]*mono[pair[1]]

    if expected == 0:

      odds [pair]=0

    else:

      odds [pair ]=observed/expected

  return odds

In [ ]:
sequence = "ATCGATCG"

ratio = odds_ratio(sequence)

print(ratio)

{'AA': 0.0, 'AT': 4.571428571428571, 'AG': 0.0, 'AC': 0.0, 'TA': 0.0, 'TT': 0.0, 'TG': 0.0, 'TC': 4.571428571428571, 'GA': 2.2857142857142856, 'GT': 0.0, 'GG': 0.0, 'GC': 0.0, 'CA': 0.0, 'CT': 0.0, 'CG': 4.571428571428571, 'CC': 0.0}